# Generated by Django 6.0.5 on 2026-06-08 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("interactions", "0001_initial"),
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="follow",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followed_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="follow",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="postclick",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clicks",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="postclick",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clicks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="postimpression",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="impressions",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="postimpression",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="impressions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="postlike",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="postlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["follower", "author"], name="follow_followe_ffc30f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postclick",
            index=models.Index(
                fields=["user", "post"], name="post_click_user_id_aeec1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postclick",
            index=models.Index(
                fields=["user", "created_at"], name="post_click_user_id_aee0a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postimpression",
            index=models.Index(
                fields=["user", "post"], name="post_impres_user_id_3e58b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postimpression",
            index=models.Index(
                fields=["user", "created_at"], name="post_impres_user_id_49ba47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postlike",
            index=models.Index(
                fields=["user", "post"], name="post_like_user_id_d657ed_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="postlike",
            unique_together={("user", "post")},
        ),
    ]
