user_persona = [
    {"age": 24, "persona": "프로 배낭러"},
    {"age": 21, "persona": "프로 뚜벅이"},
    {"age": 34, "persona": "호캉스 마스터"},
    {"age": 29, "persona": "전국 맛집 헌터"},
    {"age": 27, "persona": "감성 카페 투어러"},
    {"age": 38, "persona": "주말 캠핑 러버"},
    {"age": 23, "persona": "사진 한 장에 진심인 인생샷러"},
    {"age": 31, "persona": "혼행 마니아"},
    {"age": 26, "persona": "가성비 여행 끝판왕"},
    {"age": 45, "persona": "럭셔리 트래블러"},
    {"age": 22, "persona": "액티비티 중독자"},
    {"age": 36, "persona": "역사 유적 탐방러"},
    {"age": 41, "persona": "미식 여행가"},
    {"age": 33, "persona": "워케이션 디지털 노마드"},
    {"age": 39, "persona": "아이 둘 데리고 다니는 가족 여행 플래너"},
    {"age": 28, "persona": "캠핑카 유목민"},
    {"age": 30, "persona": "주말마다 산 타는 등산 마니아"},
    {"age": 25, "persona": "서핑하러 바다만 찾아다니는 바다 러버"},
    {"age": 35, "persona": "야경 명소 헌터"},
    {"age": 52, "persona": "전통시장 골목 탐험가"},
    {"age": 48, "persona": "온천·스파 힐링러"},
    {"age": 23, "persona": "음악 페스티벌 추적자"},
    {"age": 32, "persona": "미술관·전시 순례자"},
    {"age": 27, "persona": "로컬 체험 덕후"},
    {"age": 29, "persona": "자전거로 국토종주하는 라이더"},
    {"age": 44, "persona": "기차 여행 낭만파"},
    {"age": 24, "persona": "겨울만 기다리는 스키·보드 매니아"},
    {"age": 37, "persona": "스쿠버 다이빙 애호가"},
    {"age": 55, "persona": "사찰·템플스테이 순례자"},
    {"age": 42, "persona": "와이너리 투어러"},
    {"age": 28, "persona": "별 보러 다니는 천문 덕후"},
    {"age": 26, "persona": "폐역·이색 명소 탐험가"},
    {"age": 33, "persona": "반려견 동반 여행러"},
    {"age": 30, "persona": "미니멀 초경량 백패커"},
    {"age": 46, "persona": "면세점 쇼핑이 여행의 절반인 쇼핑러"},
    {"age": 58, "persona": "주말 골프 여행족"},
    {"age": 60, "persona": "크루즈 여행 즐기는 시니어 트래블러"},
    {"age": 34, "persona": "당일치기 드라이브 코스 마스터"},
    {"age": 25, "persona": "디저트 카페만 골라 다니는 빵지순례러"},
    {"age": 40, "persona": "캠퍼밴 끌고 다니는 차박 부부"},
]