# Generated by Django 6.0.5 on 2026-06-08 07:03

import apps.core.utils.ulid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.core.utils.ulid.generate_ulid,
                        editable=False,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.CharField(blank=True, max_length=100, null=True)),
                ("img_key", models.CharField(blank=True, max_length=255, null=True)),
                ("original_img", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "comment",
            },
        ),
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.core.utils.ulid.generate_ulid,
                        editable=False,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "comment_like",
            },
        ),
    ]
