# Generated by Django 6.0.5 on 2026-06-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_usertaste"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertaste",
            name="alpha",
            field=models.FloatField(default=0.0),
        ),
    ]
