# Generated by Django 6.0.5 on 2026-06-14 14:22

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_usertaste_alpha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertaste",
            name="vector",
            field=pgvector.django.vector.VectorField(dimensions=1024),
        ),
    ]
