# Generated by Django 6.0.5 on 2026-06-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_usertaste_vector"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertaste",
            name="vector",
        ),
    ]
