# Generated by Django 6.0.5 on 2026-06-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_usertaste_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertaste",
            name="codebook_version",
            field=models.CharField(default="v1", max_length=16),
        ),
        migrations.AddField(
            model_name="usertaste",
            name="codeword_counts",
            field=models.JSONField(default=dict),
        ),
    ]
