# Generated by Django 6.0.5 on 2026-06-08 07:03

import apps.core.utils.ulid
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.core.utils.ulid.generate_ulid,
                        editable=False,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address_name", models.CharField(max_length=255)),
                ("road_address_name", models.CharField(max_length=255)),
                ("place_name", models.CharField(max_length=255)),
                ("x", models.DecimalField(decimal_places=14, max_digits=17)),
                ("y", models.DecimalField(decimal_places=14, max_digits=17)),
            ],
            options={
                "db_table": "locations",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.core.utils.ulid.generate_ulid,
                        editable=False,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField(blank=True, default="")),
                ("thumbnail", models.TextField(blank=True, default="")),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=384, null=True
                    ),
                ),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("comment_count", models.PositiveIntegerField(default=0)),
                ("view_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "posts",
            },
        ),
        migrations.CreateModel(
            name="PostSpot",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.core.utils.ulid.generate_ulid,
                        editable=False,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "post_spots",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PostSpotImage",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.core.utils.ulid.generate_ulid,
                        editable=False,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("img_key", models.TextField()),
                ("original_img", models.TextField()),
                ("img_order", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "post_spot_images",
                "ordering": ["img_order"],
            },
        ),
    ]
