# Generated by Django 6.0.5 on 2026-06-12 08:12

import apps.posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_remove_post_embedding_postembedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="random_score",
            field=models.FloatField(db_index=True, default=apps.posts.models.get_random),
        ),
    ]
