# Generated by Django 6.0.5 on 2026-06-14 14:22

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_random_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postembedding",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1024, null=True
            ),
        ),
        migrations.AlterField(
            model_name="postembedding",
            name="raw_embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1024, null=True
            ),
        ),
    ]
