# Generated by Django 6.0.5 on 2026-06-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_postembedding_embedding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postembedding",
            name="codebook_version",
            field=models.CharField(blank=True, default="v1", max_length=16),
        ),
        migrations.AddField(
            model_name="postembedding",
            name="codewords",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
